version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src  # Mount the local src directory into the container
      - ./lstm_autoencoder.pth:/app/lstm_autoencoder.pth  # Mount the model file
    ports:
      - "8000:8000"
    environment:
      - SERVER_URL=ws://localhost:5678
