# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir asyncio websockets numpy joblib scikit-learn==1.3.0

# Copy the model file into the container
COPY gmm_model.pkl /app/gmm_model.pkl

# Make port 8766 available to the world outside this container
EXPOSE 8766

# Run tool2.py when the container launches
CMD ["python", "tool2.py"]
