apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-stream-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - name: reader
        image: your-username/tool2:latest
        imagePullPolicy: IfNotPresent  # Ensure this is set
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
        ports:
        - containerPort: 8766

