apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-movement-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: your-username/tool1:latest
        imagePullPolicy: IfNotPresent  # Ensure this is set
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
        ports:
        - containerPort: 8765

