apiVersion: v1
kind: Service
metadata:
  name: tool2-service
spec:
  type: NodePort
  selector:
    app: tool2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002  # Specify a NodePort in the range 30000-32767
