apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool1
spec:
  replicas: 3  # Increase the number of replicas for load balancing
  selector:
    matchLabels:
      app: tool1
  template:
    metadata:
      labels:
        app: tool1
    spec:
      containers:
      - name: tool1
        image: sepideh92sh/tool1:latest
        ports:
        - containerPort: 5678
        env:
        - name: NUM_ANIMALS
          valueFrom:
            configMapKeyRef:
              name: tool1-config
              key: NUM_ANIMALS
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: tool1-service
spec:
  selector:
    app: tool1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
      nodePort: 30001  # Ensure this is within the NodePort range (30000-32767)
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tool1-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: tool1.example.com  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tool1-service
            port:
              number: 80
