# deployment-tool2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tool2
  template:
    metadata:
      labels:
        app: tool2
    spec:
      containers:
      - name: tool2
        image: sepideh92sh/tool2:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: tool2-config
              key: SERVER_URL
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: tool2-service
spec:
  selector:
    app: tool2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
