apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tool1
  template:
    metadata:
      labels:
        app: tool1
    spec:
      containers:
      - name: tool1
        image: sepideh92sh/tool1:latest
        ports:
        - containerPort: 5678
        env:
        - name: NUM_ANIMALS
          valueFrom:
            configMapKeyRef:
              name: tool1-config
              key: NUM_ANIMALS
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: tool1-service
spec:
  selector:
    app: tool1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
      nodePort: 30001  # Ensure this is within the NodePort range (30000-32767)
