apiVersion: v1
kind: Service
metadata:
  name: tool1-service
spec:
  type: NodePort
  selector:
    app: tool1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001  # Specify a NodePort in the range 30000-32767
